#!/bin/bash
# =============================================================================
# Polymarket Multi-Strategy Bot — VPS Deployment Script
#
# Run this on a fresh VPS (Ubuntu 22.04/24.04, Debian 12, or similar):
#   curl -sSL <raw-url> | bash
#   OR: scp this file to VPS and run: bash deploy.sh
#
# Recommended: Vultr London $6/mo or Oracle Cloud Free Tier (London/Frankfurt)
# =============================================================================

set -euo pipefail

REPO_DIR="$HOME/amibot"
PYTHON_MIN="3.11"
SERVICE_NAME="amibot"

echo "============================================"
echo "  Polymarket Bot — VPS Deployment"
echo "============================================"
echo ""

# ---- 1. System packages ----
echo "[1/6] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq python3 python3-pip python3-venv git curl > /dev/null 2>&1

# Check Python version
PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "  Python version: $PY_VERSION"

# ---- 2. Clone or update repo ----
echo "[2/6] Setting up repository..."
if [ -d "$REPO_DIR" ]; then
    echo "  Repo exists — pulling latest..."
    cd "$REPO_DIR"
    git pull origin main 2>/dev/null || git pull 2>/dev/null || true
else
    echo "  Cloning repo..."
    # If deploying from a git remote:
    # git clone <your-repo-url> "$REPO_DIR"
    # For now, assume the code is already transferred (scp/rsync)
    echo "  NOTE: Copy your code to $REPO_DIR first, then re-run this script."
    echo "  Example: rsync -avz --exclude='.env' ./ user@your-vps:~/amibot/"
    mkdir -p "$REPO_DIR"
fi

cd "$REPO_DIR"

# ---- 3. Python virtual environment ----
echo "[3/6] Setting up Python environment..."
if [ ! -d "venv" ]; then
    python3 -m venv venv
fi
source venv/bin/activate

pip install --upgrade pip -q
pip install -r requirements.txt -q 2>&1 | tail -1

echo "  Installed $(pip list 2>/dev/null | wc -l) packages"

# ---- 4. Network connectivity test ----
echo "[4/6] Testing network connectivity..."
echo ""

# Test Binance WebSocket
WS_OK=false
python3 -c "
import asyncio, websockets, json, time
async def test():
    start = time.time()
    try:
        async with websockets.connect('wss://stream.binance.com:9443/ws/btcusdt@trade', close_timeout=3, open_timeout=5) as ws:
            msg = await asyncio.wait_for(ws.recv(), timeout=5)
            data = json.loads(msg)
            latency = (time.time() - start) * 1000
            price = float(data.get('p', 0))
            print(f'  Binance WS:       OK  ({latency:.0f}ms, BTC=\${price:.0f})')
            return True
    except Exception as e:
        print(f'  Binance WS:       BLOCKED ({e})')
        return False
result = asyncio.run(test())
exit(0 if result else 1)
" && WS_OK=true || true

# Test Kraken REST
python3 -c "
import httpx, time
start = time.time()
try:
    r = httpx.get('https://api.kraken.com/0/public/Ticker?pair=XBTUSD', timeout=5)
    latency = (time.time() - start) * 1000
    print(f'  Kraken REST:      OK  ({latency:.0f}ms, status={r.status_code})')
except Exception as e:
    print(f'  Kraken REST:      FAIL ({e})')
" || true

# Test Polymarket CLOB
python3 -c "
import httpx, time
start = time.time()
try:
    r = httpx.get('https://clob.polymarket.com/time', timeout=5)
    latency = (time.time() - start) * 1000
    print(f'  Polymarket CLOB:  OK  ({latency:.0f}ms, status={r.status_code})')
except Exception as e:
    print(f'  Polymarket CLOB:  FAIL ({e})')
" || true

# Test Polymarket Gamma API
python3 -c "
import httpx, time
start = time.time()
try:
    r = httpx.get('https://gamma-api.polymarket.com/markets?limit=1', timeout=5)
    latency = (time.time() - start) * 1000
    print(f'  Gamma API:        OK  ({latency:.0f}ms, status={r.status_code})')
except Exception as e:
    print(f'  Gamma API:        FAIL ({e})')
" || true

# Test geo-block status
python3 -c "
import httpx
try:
    r = httpx.get('https://polymarket.com/api/geoblock', timeout=5)
    data = r.json()
    blocked = data.get('blocked', 'unknown')
    print(f'  Geo-block check:  blocked={blocked}')
except Exception as e:
    print(f'  Geo-block check:  could not verify ({e})')
" || true

echo ""
if [ "$WS_OK" = true ]; then
    echo "  >>> WebSocket mode available — sub-10ms price updates <<<"
else
    echo "  >>> REST-only mode — 500ms updates (WebSocket blocked) <<<"
fi
echo ""

# ---- 5. Environment config ----
echo "[5/6] Checking configuration..."
if [ ! -f ".env" ]; then
    echo "  Creating default .env (paper trading mode)..."
    cat > .env << 'ENVEOF'
# Polymarket Multi-Strategy Bot Configuration
# Generated by deploy.sh

# Your Polygon wallet private key (with 0x prefix)
# Leave as-is for paper trading, set real key for live trading
PRIVATE_KEY=0xYOUR_PRIVATE_KEY_HERE

# Polymarket CLOB API credentials (auto-derived from private key if empty)
POLY_API_KEY=
POLY_API_SECRET=
POLY_PASSPHRASE=

# === OPERATING MODE ===
DRY_RUN=true
PAPER_BALANCE=100

# === STRATEGY ===
STRATEGY=unified
POSITION_USD=10
MAX_POSITION_SIZE=15
MAX_EXPOSURE_USDC=30
MIN_EDGE_THRESHOLD=0.05
CONFIDENCE_THRESHOLD=0.60
MAKER_ONLY=true
PREFER_15MIN=true

# === RISK MANAGEMENT ===
MAX_CONSECUTIVE_LOSSES=4
DAILY_LOSS_LIMIT_USDC=15
COOLDOWN_AFTER_LOSS_STREAK_SECONDS=300
MAX_POSITIONS_PER_INTERVAL=2

# === BANKROLL PROTECTION ===
MAX_PCT_PER_TRADE=0.05
MAX_PCT_PER_INTERVAL=0.10
MAX_PCT_TOTAL_EXPOSURE=0.30
DRAWDOWN_HALT_PCT=0.15
BALANCE_REFRESH_INTERVAL=30

# === EXECUTION ===
FILL_CHECK_INTERVAL=3
ORDER_TIMEOUT=45

# === LOGGING ===
LOG_LEVEL=INFO
LOG_FILE=bot.log
TRADE_LOG=trades.jsonl
ENVEOF
    echo "  Default .env created (paper trading, $100 balance)"
else
    echo "  .env already exists — keeping current config"
fi

# ---- 6. Systemd service ----
echo "[6/6] Setting up systemd service..."

VENV_PYTHON="$REPO_DIR/venv/bin/python3"

sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << SERVICEEOF
[Unit]
Description=Polymarket Multi-Strategy Trading Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$REPO_DIR
ExecStart=$VENV_PYTHON $REPO_DIR/run.py
Restart=always
RestartSec=10
StandardOutput=append:$REPO_DIR/bot_output.log
StandardError=append:$REPO_DIR/bot_output.log

# Restart limits
StartLimitIntervalSec=600
StartLimitBurst=10

# Environment
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
SERVICEEOF

sudo systemctl daemon-reload
sudo systemctl enable ${SERVICE_NAME} 2>/dev/null || true

echo ""
echo "============================================"
echo "  Deployment Complete!"
echo "============================================"
echo ""
echo "  Quick start:"
echo "    cd $REPO_DIR"
echo "    source venv/bin/activate"
echo "    python run.py                    # Run in foreground"
echo ""
echo "  Or run as a service (24/7):"
echo "    sudo systemctl start amibot      # Start bot"
echo "    sudo systemctl status amibot     # Check status"
echo "    journalctl -u amibot -f          # Live logs"
echo "    tail -f $REPO_DIR/bot.log        # Bot log"
echo "    tail -f $REPO_DIR/trades.jsonl   # Trade log"
echo ""
echo "  Configuration:"
echo "    nano $REPO_DIR/.env              # Edit config"
echo "    sudo systemctl restart amibot    # Apply changes"
echo ""
echo "  To go live (real money):"
echo "    1. Fund a Polygon wallet with USDC"
echo "    2. Set PRIVATE_KEY in .env"
echo "    3. Set DRY_RUN=false"
echo "    4. Restart: sudo systemctl restart amibot"
echo ""
